---
# tasks file for vector
- name: Get vector distrib
  get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"

- name: Install vector package
  yum:
    name:
      - vector-{{ vector_version }}-1.x86_64.rpm
    disable_gpg_check: True

- name: Server configuration file
  template:
    src: vector.toml.j2
    dest: "/etc/vector/vector.toml"
    owner: "root"
    group: "root"
    mode: "0664"
  notify: Start vector service
